/*
Copyright 2025 The Hyperlight Authors.
Modifications Copyright 2026 The picolibc-rs Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//! Build script for the `picolibc` crate.
//!
//! Compiles picolibc-bsd from source with cc-rs, statically links the result,
//! generates `OUT_DIR/include/picolibc.h` reflecting the active cargo features,
//! optionally runs bindgen, and exports the include directory to dependents.

mod build_files;

use std::path::{Path, PathBuf};
use std::process::Command;
use std::{env, fs};

use anyhow::{bail, Context, Result};
#[cfg(feature = "posix-console")]
use build_files::LIBC_FILES_POSIX_CONSOLE;
use build_files::{
    LIBC_FILES, LIBC_FILES_AARCH64_ASM, LIBC_FILES_AARCH64_C, LIBC_FILES_AARCH64_EXCLUDE,
    LIBC_FILES_X86, LIBM_FILES, LIBM_FILES_X86,
};

// ---------------------------------------------------------------------------
// picolibc.h generation
// ---------------------------------------------------------------------------

/// Write `$OUT_DIR/include/picolibc.h` with the exact macro set that matches
/// the active cargo features. This replaces the former static `include/picolibc.h`.
///
/// Upstream picolibc normally generates this file from meson options; we do the
/// same thing here, driven by cargo feature flags.
fn generate_picolibc_h(include_dir: &Path) -> Result<()> {
    // Helper: either `#define NAME` or `#undef NAME` based on a boolean.
    fn define(h: &mut String, name: &str, enable: bool) {
        if enable {
            h.push_str(&format!("#define {name}\n"));
        } else {
            h.push_str(&format!("#undef  {name}\n"));
        }
    }

    let mut h = String::new();

    h.push_str("/* Auto-generated by build.rs — do not edit by hand.\n");
    h.push_str(" * Re-run `cargo build` after changing cargo features.\n");
    h.push_str(" * Corresponds to upstream picolibc's meson-generated picolibc.h.\n");
    h.push_str(" */\n\n");
    h.push_str("#pragma once\n\n");

    // ── version ──────────────────────────────────────────────────────────────
    h.push_str("/* version */\n");
    h.push_str("#define _NEWLIB_VERSION \"4.3.0\"\n");
    h.push_str("#define __NEWLIB_VERSION__ \"4.3.0\"\n");
    h.push_str("#define __NEWLIB__ 4\n");
    h.push_str("#define __NEWLIB_MINOR__ 3\n");
    h.push_str("#define __NEWLIB_PATCHLEVEL__ 0\n");
    h.push_str("#define __PICOLIBC_VERSION__ \"1.8.11\"\n");
    h.push_str("#define __PICOLIBC__ 1\n");
    h.push_str("#define __PICOLIBC_MINOR__ 8\n");
    h.push_str("#define __PICOLIBC_PATCHLEVEL__ 11\n\n");

    // ── always-on (freestanding/baremetal invariants) ─────────────────────────
    h.push_str("/* freestanding invariants — not user-configurable */\n");
    // single-thread: we target baremetal with no RTOS threading model
    h.push_str("#define __SINGLE_THREAD\n");
    // global errno: no TLS, single thread
    h.push_str("#define __GLOBAL_ERRNO\n");
    // initfini-array: all modern baremetal toolchains support this
    h.push_str("#define __INIT_FINI_ARRAY\n");
    // tiny stdio: only stdio picolibc ships since 1.8
    h.push_str("#define __TINY_STDIO\n");
    // format-default=double ('d')
    h.push_str("#define __IO_DEFAULT 'd'\n");
    // avoid software division in decimal conversion (always a win on baremetal)
    h.push_str("#define __IO_SMALL_ULTOA\n");
    // semihosting: off — use POSIX read/write stubs or posix-console feature
    h.push_str("#undef  __ARM_SEMIHOST\n");
    h.push_str("#undef  __SEMIHOST\n");
    // TLS: off — no runtime support on baremetal
    h.push_str("#undef  __THREAD_LOCAL_STORAGE\n");
    h.push_str("#undef  __THREAD_LOCAL_STORAGE_API\n");
    h.push_str("#undef  __THREAD_LOCAL_STORAGE_RP2040\n");
    h.push_str("#undef  __THREAD_LOCAL_STORAGE_STACK_GUARD\n");
    // picolibc's own malloc: off — embedder provides malloc (or use `malloc` feature)
    h.push_str("#undef  __ENABLE_MALLOC\n");
    h.push_str("#undef  __MALLOC_CLEAR_FREED\n");
    // fcntl: off — freestanding
    h.push_str("#undef  __HAVE_FCNTL\n");
    // stdio locking: off — single thread
    h.push_str("#undef  __STDIO_LOCKING\n");
    // atomic ungetc: off — single thread
    h.push_str("#undef  __ATOMIC_UNGETC\n");
    // obsolete math: off
    h.push_str("#undef  __OBSOLETE_MATH\n");
    h.push_str("#undef  __OBSOLETE_MATH_DOUBLE\n");
    h.push_str("#undef  __OBSOLETE_MATH_FLOAT\n");
    // size-over-speed: off — release build
    h.push_str("#undef  __PREFER_SIZE_OVER_SPEED\n");
    // legacy init/fini functions: off (use INIT_FINI_ARRAY instead)
    h.push_str("#undef  __INIT_FINI_FUNCS\n");
    h.push_str("#undef  __IEEEFP_FUNCS\n");
    h.push_str("#undef  __HAVE_BITFIELDS_IN_PACKED_STRUCTS\n");
    h.push('\n');

    // ── cargo-feature-controlled options ─────────────────────────────────────
    h.push_str("/* cargo-feature-controlled options */\n");

    // assert-verbose: emit file/line info in assert() failures
    define(&mut h, "__ASSERT_VERBOSE", cfg!(feature = "assert-verbose"));

    // fast-strcmp: optimise strcmp for speed (vs size)
    define(&mut h, "__FAST_STRCMP", cfg!(feature = "fast-strcmp"));

    // fast-bufio: faster buffered I/O operations
    define(&mut h, "__FAST_BUFIO", cfg!(feature = "fast-bufio"));

    // io-float-exact: round-trip accurate float/string conversion
    define(&mut h, "__IO_FLOAT_EXACT", cfg!(feature = "io-float-exact"));

    // io-wchar: wide-character support in printf/scanf
    define(&mut h, "__IO_WCHAR", cfg!(feature = "io-wchar"));

    // io-c99-formats: %zu, %hhu, %td, %jd, etc.
    define(&mut h, "__IO_C99_FORMATS", cfg!(feature = "io-c99-formats"));

    // io-long-long: %lld/%llu/%llo/%llx in printf/scanf
    define(&mut h, "__IO_LONG_LONG", cfg!(feature = "io-long-long"));

    // io-long-double: %Lf/%Le/%Lg in printf/scanf
    define(&mut h, "__IO_LONG_DOUBLE", cfg!(feature = "io-long-double"));

    // io-pos-args: positional arguments (%1$d) in printf
    define(&mut h, "__IO_POS_ARGS", cfg!(feature = "io-pos-args"));

    // io-percent-b: %b/%B binary integer format (C23)
    define(&mut h, "__IO_PERCENT_B", cfg!(feature = "io-percent-b"));

    // printf-percent-n: %n in printf (off by default for security)
    define(&mut h, "__IO_PERCENT_N", cfg!(feature = "printf-percent-n"));

    // minimal-io-long-long: %lld in the minimal printf/scanf variant
    define(
        &mut h,
        "__IO_MINIMAL_LONG_LONG",
        cfg!(feature = "minimal-io-long-long"),
    );

    // mb-capable: multibyte / UTF-8 charset support
    define(&mut h, "__MB_CAPABLE", cfg!(feature = "mb-capable"));

    // math-errno: set errno in math functions per C standard.
    // When off, IEEE mode (__IEEE_LIBM) is used — no errno side-effects.
    let math_errno = cfg!(feature = "math-errno");
    define(&mut h, "__MATH_ERRNO", math_errno);
    define(&mut h, "__IEEE_LIBM", !math_errno);
    h.push('\n');

    // ── compiler feature detection (unchanged from upstream) ─────────────────
    h.push_str("/* compiler built-in feature detection */\n");
    h.push_str(
        r#"
#ifndef __has_builtin
#define picolibc_has_builtin(x) 0
#else
#define picolibc_has_builtin(x) __has_builtin(x)
#endif

#if picolibc_has_builtin(__builtin_alloca)
#define __HAVE_BUILTIN_ALLOCA 1
#endif
#if picolibc_has_builtin(__builtin_ffs)
#define __HAVE_BUILTIN_FFS 1
#endif
#if picolibc_has_builtin(__builtin_ffsl)
#define __HAVE_BUILTIN_FFSL 1
#endif
#if picolibc_has_builtin(__builtin_ffsll)
#define __HAVE_BUILTIN_FFSLL 1
#endif
#if picolibc_has_builtin(__builtin_ctz)
#define __HAVE_BUILTIN_CTZ 1
#endif
#if picolibc_has_builtin(__builtin_ctzl)
#define __HAVE_BUILTIN_CTZL 1
#endif
#if picolibc_has_builtin(__builtin_ctzll)
#define __HAVE_BUILTIN_CTZLL 1
#endif
#if picolibc_has_builtin(__builtin_copysign)
#define __HAVE_BUILTIN_COPYSIGN 1
#endif
#if picolibc_has_builtin(__builtin_copysignl)
#define __HAVE_BUILTIN_COPYSIGNL 1
#endif
#if picolibc_has_builtin(__builtin_isinf)
#define __HAVE_BUILTIN_ISINF 1
#endif
#if picolibc_has_builtin(__builtin_isinfl)
#define __HAVE_BUILTIN_ISINFL 1
#endif
#if picolibc_has_builtin(__builtin_isnan)
#define __HAVE_BUILTIN_ISNAN 1
#endif
#if picolibc_has_builtin(__builtin_isnanl)
#define __HAVE_BUILTIN_ISNANL 1
#endif
#if picolibc_has_builtin(__builtin_isfinite)
#define __HAVE_BUILTIN_ISFINITE 1
#endif
#if picolibc_has_builtin(__builtin_finitel)
#define __HAVE_BUILTIN_FINITEL 1
#endif
#if picolibc_has_builtin(__builtin_issignalingl)
#define __HAVE_BUILTIN_ISSIGNALINGL 1
#endif
#if picolibc_has_builtin(__builtin_expect)
#define __HAVE_BUILTIN_EXPECT 1
#endif
#if picolibc_has_builtin(__builtin_complex)
#define __HAVE_BUILTIN_COMPLEX 1
#endif
#if picolibc_has_builtin(__builtin_add_overflow)
#define __HAVE_BUILTIN_ADD_OVERFLOW 1
#endif
#if picolibc_has_builtin(__builtin_mul_overflow)
#define __HAVE_BUILTIN_MUL_OVERFLOW 1
#endif

#if !defined(__STDC_NO_COMPLEX__)
#define __HAVE_COMPLEX 1
#endif

#undef picolibc_has_builtin
"#,
    );

    fs::write(include_dir.join("picolibc.h"), &h)
        .context("could not write generated picolibc.h")?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Architecture configuration
// ---------------------------------------------------------------------------

struct ArchConfig {
    libc_machine: Vec<&'static str>,
    libm_machine: Vec<&'static str>,
    /// Generic `LIBC_FILES` entries replaced by machine sources (drop to avoid
    /// duplicate symbols).
    libc_generic_exclude: Vec<&'static str>,
    /// Machine libc sources that must be dropped on COFF/Win64 (ELF asm).
    coff_excluded_libc: Vec<&'static str>,
    include_dirs: Vec<&'static str>,
    /// `libc/machine/<arch>/machine/` directory, relative to the picolibc root.
    ///
    /// The arch-specific `machine/*.h` headers (e.g. `machine/fenv.h` with the
    /// struct-based `fenv_t` for x86) must shadow the generic
    /// `libc/include/machine/` headers in `OUT_DIR/include/machine/`. Without
    /// this override the generic `typedef int fenv_t` is found first, causing
    /// the x86 `libm/machine/x86/fenv.c` to fail to compile.
    machine_headers_dir: Option<&'static str>,
    is_x86: bool,
    is_aarch64: bool,
}

fn arch_config(target_arch: &str) -> Result<ArchConfig> {
    match target_arch {
        "x86" | "x86_64" => Ok(ArchConfig {
            libc_machine: LIBC_FILES_X86.to_vec(),
            libm_machine: LIBM_FILES_X86.to_vec(),
            libc_generic_exclude: Vec::new(),
            coff_excluded_libc: vec![
                "machine/x86/interrupt.S",
                "machine/x86/setjmp.S",
                "machine/x86/tcb.S",
            ],
            include_dirs: vec!["libc/machine/x86", "libm/machine/x86"],
            machine_headers_dir: Some("libc/machine/x86/machine"),
            is_x86: true,
            is_aarch64: false,
        }),
        "aarch64" => Ok(ArchConfig {
            libc_machine: LIBC_FILES_AARCH64_C
                .iter()
                .chain(LIBC_FILES_AARCH64_ASM.iter())
                .copied()
                .collect(),
            libm_machine: Vec::new(),
            libc_generic_exclude: LIBC_FILES_AARCH64_EXCLUDE.to_vec(),
            coff_excluded_libc: LIBC_FILES_AARCH64_ASM.to_vec(),
            include_dirs: vec!["libc/machine/aarch64"],
            machine_headers_dir: Some("libc/machine/aarch64/machine"),
            is_x86: false,
            is_aarch64: true,
        }),
        arch => bail!(
            "picolibc: unsupported target architecture {arch:?}. \
             Only x86/x86_64 and aarch64 are wired up so far; see arch_config() \
             in build.rs to add another architecture."
        ),
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Recursively copy every `*.h` under `base` into `include_dir`, skipping any
/// file whose name appears in `skip`.
fn copy_includes(include_dir: &Path, base: &Path, skip: &[&str]) -> Result<()> {
    let entries =
        fs::read_dir(base).with_context(|| format!("could not open include dir {base:?}"))?;
    for entry in entries {
        let entry = entry.with_context(|| format!("could not read include dir {base:?}"))?;
        let src = entry.path();
        if skip
            .iter()
            .any(|s| src.file_name() == Some(std::ffi::OsStr::new(s)))
        {
            continue;
        }
        let dst = include_dir.join(entry.file_name());
        let kind = entry
            .file_type()
            .with_context(|| format!("could not find type of {src:?}"))?;
        if kind.is_dir() {
            fs::create_dir_all(&dst)
                .with_context(|| format!("could not create include dir {dst:?}"))?;
            copy_includes(&dst, &src, skip)?;
        } else if src.extension() == Some(std::ffi::OsStr::new("h")) {
            fs::copy(&src, &dst).with_context(|| format!("could not copy header {src:?}"))?;
        }
    }
    Ok(())
}

fn init_submodule(picolibc_dir: &Path) -> Result<()> {
    if picolibc_dir.join("COPYING.picolibc").exists() {
        return Ok(());
    }
    eprintln!("picolibc: third_party/picolibc is empty, initialising submodule");
    let status = Command::new("git")
        .args(["submodule", "update", "--init", "--depth", "1"])
        .arg(picolibc_dir)
        .status()
        .context("failed to run `git submodule update --init`")?;
    if !status.success() {
        bail!(
            "`git submodule update --init {}` failed; check out the picolibc \
             submodule manually",
            picolibc_dir.display()
        );
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Compilation
// ---------------------------------------------------------------------------

fn cc_build(
    picolibc_dir: &Path,
    out_include_dir: &Path,
    arch: &ArchConfig,
    coff: bool,
) -> Result<cc::Build> {
    let mut build = cc::Build::new();

    let compiler = env::var("PICOLIBC_CC")
        .or_else(|_| env::var("CC"))
        .unwrap_or_else(|_| "clang".to_string());
    build.compiler(compiler);

    if let Ok(t) = env::var("PICOLIBC_CLANG_TARGET") {
        build.flag(format!("--target={t}"));
    }

    build
        .std("c18")
        .flag("-ffreestanding")
        .flag("-nostdlibinc")
        .flag("-fno-builtin")
        .flag("-fno-common")
        .flag("-fno-stack-protector")
        .flag("-U_FORTIFY_SOURCE")
        .flag("-Wno-unused-command-line-argument")
        .flag("-Wno-implicit-int")
        .flag("-Wno-missing-braces")
        .flag("-Wno-return-type")
        .warnings(false);

    if arch.is_x86 {
        build.flag_if_supported("-mno-red-zone");
    }
    if arch.is_aarch64 && coff {
        build.flag("-march=armv8-a+nosimd");
    }

    build
        .define("_LIBC", None)
        .define("_FILE_OFFSET_BITS", "64")
        .define("DEFINE_MEMALIGN", "1")
        .define("DEFINE_POSIX_MEMALIGN", "1");

    // picolibc.h is the generated one in OUT_DIR/include — must come first.
    build.include(out_include_dir);
    for dir in &arch.include_dirs {
        build.include(picolibc_dir.join(dir));
    }
    build
        .include(picolibc_dir)
        .include(picolibc_dir.join("libc/stdio"))
        .include(picolibc_dir.join("libc/locale"))
        .include(picolibc_dir.join("libc/include"));

    Ok(build)
}

fn add_libc(build: &mut cc::Build, picolibc_dir: &Path, arch: &ArchConfig, coff: bool) {
    for file in LIBC_FILES.iter().chain(arch.libc_machine.iter()) {
        if arch.libc_generic_exclude.contains(file) {
            continue;
        }
        if coff && arch.coff_excluded_libc.contains(file) {
            continue;
        }
        build.file(picolibc_dir.join("libc").join(file));
    }
}

/// Add the POSIX-fd-backed stdin/stdout/stderr sources (`posixiob_*.c`), gated
/// on the `posix-console` feature.
///
/// With the `coff` feature enabled, the sources are patched on the fly so that
/// `stdin`/`stdout`/`stderr` are exported as *strong* aliases of `__posix_std*`
/// instead of weak ones. picolibc's `__weak_reference` expands, on a COFF/clang
/// target, to a Mach-O `.weak_reference` directive that yields a broken weak
/// external — the COFF linker then reports the symbol as a duplicate. Rewriting
/// `__weak_reference` to `__strong_reference` (`__attribute__((alias))`) emits a
/// single normal strong symbol, which links cleanly on COFF/PE.
#[cfg(feature = "posix-console")]
fn add_posix_console(build: &mut cc::Build, picolibc_dir: &Path, out_dir: &Path) -> Result<()> {
    let patch = cfg!(feature = "coff");
    let patched_dir = out_dir.join("posix_console_patched");
    if patch {
        fs::create_dir_all(&patched_dir)
            .with_context(|| format!("could not create {patched_dir:?}"))?;
    }

    for file in LIBC_FILES_POSIX_CONSOLE {
        let src = picolibc_dir.join("libc").join(file);
        if patch {
            let contents =
                fs::read_to_string(&src).with_context(|| format!("could not read {src:?}"))?;
            // Turn the weak alias into a strong one. Both macros take the same
            // `(sym, alias)` arguments, so a textual swap is sufficient.
            let patched = contents.replace("__weak_reference", "__strong_reference");
            let name = Path::new(file)
                .file_name()
                .expect("posix-console source has a file name");
            let dst = patched_dir.join(name);
            fs::write(&dst, patched).with_context(|| format!("could not write {dst:?}"))?;
            build.file(&dst);
        } else {
            build.file(&src);
        }
    }
    Ok(())
}

#[cfg(not(feature = "posix-console"))]
fn add_posix_console(_: &mut cc::Build, _: &Path, _: &Path) -> Result<()> {
    Ok(())
}

fn add_libm(build: &mut cc::Build, picolibc_dir: &Path, arch: &ArchConfig) {
    build.include(picolibc_dir.join("libm/common"));
    for file in LIBM_FILES.iter().chain(arch.libm_machine.iter()) {
        build.file(picolibc_dir.join("libm").join(file));
    }
}

// ---------------------------------------------------------------------------
// Bindgen
// ---------------------------------------------------------------------------

/// Pick the clang `--target` triple bindgen should parse headers with.
///
/// It must produce the same C data model (notably the width of `long`) as both
/// the compiled library and the Rust target's `core::ffi` types — otherwise the
/// generated bindings disagree about `long`/`ssize_t`/etc. and bindgen's
/// `size_t == usize` assertion fails.
///
/// The subtlety is UEFI: clang's `*-unknown-uefi` triple is **LP64** (`long` is
/// 8 bytes), but UEFI actually uses the Windows **LLP64** ABI (`long` is 4
/// bytes). Rust's `*-unknown-uefi` targets and cc-rs (which compiles UEFI code
/// as `*-windows-gnu`) both follow LLP64. So for a `*-unknown-uefi` target we
/// hand bindgen the matching `*-windows-gnu` triple instead.
#[cfg(feature = "bindings")]
fn bindgen_clang_target() -> Option<String> {
    if let Ok(t) = env::var("PICOLIBC_CLANG_TARGET") {
        return Some(t);
    }
    let target = env::var("TARGET").ok()?;
    if let Some(prefix) = target.strip_suffix("-unknown-uefi") {
        return Some(format!("{prefix}-unknown-windows-gnu"));
    }
    Some(target)
}

#[cfg(feature = "bindings")]
fn generate_bindings(include_dir: &Path, out_dir: &Path) -> Result<()> {
    use bindgen::Formatter::Prettyplease;
    use bindgen::RustEdition::Edition2021;

    let header = |name: &str| include_dir.join(name).to_string_lossy().into_owned();

    let mut builder = bindgen::Builder::default();
    for h in [
        "stdlib.h",
        "stdio.h",
        "string.h",
        "math.h",
        "stdint.h",
        "ctype.h",
        "errno.h",
        "time.h",
        "limits.h",
        "signal.h",
        "setjmp.h",
        "locale.h",
        "wchar.h",
        "wctype.h",
        "fenv.h",
        "inttypes.h",
        "sys/time.h",
    ] {
        builder = builder.header(header(h));
    }

    builder = builder
        .clang_arg(format!("-I{}", include_dir.display()))
        .clang_arg("-nostdlibinc")
        .clang_arg("-ffreestanding")
        .use_core()
        .ctypes_prefix("core::ffi")
        .wrap_unsafe_ops(true)
        .rust_edition(Edition2021)
        .formatter(Prettyplease)
        .derive_copy(true)
        .derive_debug(true)
        .derive_default(true)
        .generate_comments(true)
        .generate_cstr(true)
        .layout_tests(false);

    if let Some(t) = bindgen_clang_target() {
        builder = builder.clang_arg(format!("--target={t}"));
    }

    builder
        .generate()
        .context("unable to generate bindings")?
        .write_to_file(out_dir.join("bindings.rs"))
        .context("couldn't write bindings.rs")?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

fn main() -> Result<()> {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=build_files.rs");
    // picolibc.h is now generated — it changes whenever any cargo feature changes.
    // Cargo already triggers a rebuild on feature changes, so no extra entry needed.
    println!("cargo:rerun-if-changed=third_party/picolibc/COPYING.picolibc");
    println!("cargo:rerun-if-env-changed=PICOLIBC_CC");
    println!("cargo:rerun-if-env-changed=PICOLIBC_CLANG_TARGET");

    let out_dir = PathBuf::from(env::var("OUT_DIR").context("OUT_DIR not set")?);
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").context("CARGO_MANIFEST_DIR not set")?);
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").context("CARGO_CFG_TARGET_ARCH not set")?;
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let coff = matches!(target_os.as_str(), "uefi" | "windows");

    let picolibc_dir = manifest_dir.join("third_party/picolibc");
    init_submodule(&picolibc_dir)?;

    let arch = arch_config(&target_arch)?;

    // 1. Generate picolibc.h into OUT_DIR/include *before* compilation so that
    //    cc-rs can find it.
    let include_dir = out_dir.join("include");
    fs::create_dir_all(&include_dir)
        .with_context(|| format!("could not create {include_dir:?}"))?;
    generate_picolibc_h(&include_dir)?;

    // 2. Compile picolibc (libc + libm).
    let mut build = cc_build(&picolibc_dir, &include_dir, &arch, coff)?;
    add_libc(&mut build, &picolibc_dir, &arch, coff);
    add_posix_console(&mut build, &picolibc_dir, &out_dir)?;
    add_libm(&mut build, &picolibc_dir, &arch);
    build.compile("picolibc");

    // 3. Copy picolibc's own public headers into OUT_DIR/include so downstream
    //    crates have a self-contained include tree (DEP_C_INCLUDE).
    //    The generated picolibc.h is already there and will not be overwritten
    //    (picolibc's libc/include does not contain a picolibc.h).
    copy_includes(&include_dir, &picolibc_dir.join("libc/include"), &[])?;

    // 3b. Override the generic `machine/*.h` headers with arch-specific ones.
    //
    //     `libc/include/machine/` contains generic fallbacks (e.g. `fenv.h`
    //     with `typedef int fenv_t`). The arch-specific directory (e.g.
    //     `libc/machine/x86/machine/fenv.h`) provides the real struct-based
    //     definitions needed by arch machine sources like `libm/machine/x86/fenv.c`.
    //     Since OUT_DIR/include is first in the include search path, we must
    //     overwrite those generics with the arch-specific versions here.
    //
    //     `_types.h` is deliberately NOT overridden: aarch64's machine
    //     `_types.h` hardcodes `typedef long signed int _ssize_t`, which is
    //     pointer-sized only under LP64. UEFI uses the Windows LLP64 ABI
    //     (`long` == 4 bytes), so that would make `ssize_t` 4 bytes while the
    //     pointer is 8 — breaking POSIX semantics and tripping bindgen's
    //     `size_t == usize` check. The generic `machine/_types.h` instead
    //     derives `ssize_t` from `__SIZE_TYPE__`, which is always pointer-sized.
    if let Some(machine_dir) = arch.machine_headers_dir {
        let machine_inc = include_dir.join("machine");
        fs::create_dir_all(&machine_inc)
            .with_context(|| format!("could not create {machine_inc:?}"))?;
        copy_includes(&machine_inc, &picolibc_dir.join(machine_dir), &["_types.h"])?;
    }

    // 4. Optionally generate Rust FFI bindings.
    #[cfg(feature = "bindings")]
    generate_bindings(&include_dir, &out_dir)?;

    // 5. Expose paths to dependents via cargo metadata.
    let include_str = include_dir
        .to_str()
        .context("include dir path was not valid UTF-8")?;
    println!("cargo:include={include_str}");
    println!("cargo:root={}", out_dir.display());

    Ok(())
}
