/*
Copyright 2026 The picolibc-rs Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//! Statically-linked [picolibc](https://github.com/picolibc/picolibc) for
//! baremetal Rust (UEFI, `*-none`, ...).
//!
//! Depending on this crate compiles picolibc from source and links the
//! resulting `libpicolibc.a` into your binary automatically. With the default
//! `bindings` feature enabled, the crate also re-exports `bindgen`-generated
//! Rust declarations for the libc/libm types, functions and constants (e.g.
//! [`timespec`], `EINVAL`, `CLOCK_REALTIME`, `printf`, `memcpy`).
//!
//! # Linking further C libraries
//!
//! This crate sets `links = "c"` and publishes the directory holding the C
//! headers via cargo metadata. A downstream `-sys` crate that builds its own C
//! code can read that directory from the `DEP_C_INCLUDE` environment variable
//! inside its own `build.rs` and feed it to cc-rs or the `cmake` crate:
//!
//! ```no_run
//! // In a dependent crate's build.rs (it must depend on `picolibc`):
//! let include = std::env::var("DEP_C_INCLUDE").unwrap();
//!
//! // cc-rs:
//! cc::Build::new()
//!     .include(&include)
//!     .file("vendor/foo.c")
//!     .compile("foo");
//!
//! // or the cmake crate:
//! cmake::Config::new("vendor/foo")
//!     .define("CMAKE_C_FLAGS", format!("-ffreestanding -nostdlibinc -I{include}"))
//!     .build();
//! ```
//!
//! # Required stubs
//!
//! picolibc is configured to be freestanding (single-threaded, global `errno`,
//! tiny stdio, no built-in `malloc`). The embedder must provide a small set of
//! POSIX-ish symbols at link time, typically:
//!
//! | Symbol | Purpose |
//! |--------|---------|
//! | `write` / `read` | back stdout/stderr/stdin for `printf`, `puts`, ... |
//! | `lseek` / `close` | minimal stdio plumbing (may return `-ENOSYS`) |
//! | `_exit` | terminate; called by `abort`/`exit` |
//! | `malloc` / `free` / `realloc` | back `strdup`, `asprintf`, `regcomp`, ... |
//! | `clock_gettime` | only if you call the time APIs |
//!
//! These are ordinary `#[unsafe(no_mangle)] extern "C"` Rust functions. See the
//! crate README for examples.

#![no_std]
// The generated bindings do not follow Rust naming conventions.
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]
#![allow(clippy::all)]

#[cfg(feature = "malloc")]
extern crate alloc;

/// `malloc`/`free`/`realloc`/`calloc` backed by the Rust global allocator.
///
/// Enabled by the `malloc` feature. The final binary must register a
/// `#[global_allocator]`. See the module docs for details.
#[cfg(feature = "malloc")]
pub mod malloc;

/// Raw bindings to the picolibc C headers, generated by `bindgen` at build time.
///
/// Only present when the (default) `bindings` feature is enabled.
#[cfg(feature = "bindings")]
pub mod bindings {
    #![allow(dead_code)]
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

#[cfg(feature = "bindings")]
pub use bindings::*;
