/*
The allocator implementation in this module is a port of `malloc-rust`
(https://github.com/DoumanAsh/malloc-rust) by Douman, used under the Boost
Software License 1.0. The algorithm — storing the allocation size in a header
word placed `LAYOUT_OFFSET` bytes before the pointer returned to C, and backing
everything with the Rust global allocator — is reproduced here unchanged. The
only adaptation is `DEFAULT_ALIGNMENT`, which is chosen for C conformance on the
baremetal targets this crate supports (see below), plus thin C-ABI wrappers
(`malloc`/`free`/`realloc`/`calloc`) with standard edge-case handling.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by this
license (the "Software") to use, reproduce, display, distribute, execute, and
transmit the Software, and to prepare derivative works of the Software, and to
permit third-parties to whom the Software is furnished to do so, all subject to
the following:

The copyright notices in the Software and this entire statement, including the
above license grant, this restriction and the following disclaimer, must be
included in all copies of the Software, in whole or in part, and all derivative
works of the Software, unless such copies or derivative works are solely in the
form of machine-executable object code generated by a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES
OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

//! `malloc`/`free`/`realloc`/`calloc` backed by the Rust global allocator.
//!
//! Enabled by the `malloc` feature. picolibc is built without its own allocator
//! (`__ENABLE_MALLOC` is undefined), so something must supply these symbols;
//! with this feature the crate exports them, forwarding to whatever
//! `#[global_allocator]` the final binary registers.
//!
//! **The final binary must register a `#[global_allocator]`** (baremetal/UEFI
//! has no default). Without one, the link fails with "no global memory
//! allocator found".
//!
//! Implementation ported from [`malloc-rust`](https://github.com/DoumanAsh/malloc-rust)
//! (Boost Software License 1.0): each allocation reserves a header word holding
//! the total block size, placed `LAYOUT_OFFSET` bytes before the pointer handed
//! to C, so `free`/`realloc` can recover the original `Layout`.

use alloc::alloc::Layout;
use core::ffi::c_void;
use core::{mem, ptr};

mod align {
    use core::num;

    #[derive(Copy, Clone, PartialEq, Eq)]
    #[repr(transparent)]
    /// Valid alignment representation: non-zero and a power of two.
    pub struct Alignment(num::NonZeroUsize);

    impl Alignment {
        #[inline(always)]
        /// Creates a new value, panicking if `alignment` is not a power of two.
        pub const fn new(alignment: usize) -> Self {
            assert!(alignment != 0, "Alignment cannot be zero");
            assert!(alignment.is_power_of_two());

            Self(unsafe { num::NonZeroUsize::new_unchecked(alignment) })
        }

        #[inline(always)]
        /// Returns the value at or after `size` that is a multiple of alignment.
        pub const fn next(&self, size: usize) -> usize {
            let alignment = self.0.get() - 1;
            size.saturating_add(alignment) & !alignment
        }

        #[inline(always)]
        /// Returns the raw value.
        pub const fn into_raw(&self) -> usize {
            self.0.get()
        }
    }
}

use align::Alignment;

/// Default alignment of returned allocations.
///
/// C requires `malloc` to return storage aligned for any object, i.e.
/// `_Alignof(max_align_t)` — 16 bytes on the 64-bit targets this crate supports
/// (`long double` / SIMD), 8 bytes on 32-bit. (Upstream `malloc-rust` uses 16
/// only on macOS/Win64 and 8 elsewhere; this is the conforming generalisation.)
pub const DEFAULT_ALIGNMENT: Alignment = {
    #[cfg(target_pointer_width = "64")]
    {
        Alignment::new(16)
    }
    #[cfg(not(target_pointer_width = "64"))]
    {
        Alignment::new(8)
    }
};

// It is actually fine not to store the original size, as most system allocators
// do not require it, but we cannot trust the Rust ecosystem not to screw us up.
const LAYOUT_OFFSET: usize = DEFAULT_ALIGNMENT.next(mem::size_of::<usize>());

#[cold]
#[inline(never)]
fn unlikely_null() -> *mut c_void {
    ptr::null_mut()
}

#[inline(always)]
unsafe fn get_ptr_size(ptr: *mut c_void) -> usize {
    let mem = (ptr as *mut u8).offset(-(LAYOUT_OFFSET as isize));
    let size = ptr::read(mem as *const usize);
    size.saturating_sub(LAYOUT_OFFSET)
}

/// Baseline `malloc` with the Rust allocator. Returns NULL if `size` is 0 or the
/// padded layout is invalid.
#[inline]
unsafe fn rust_malloc(mut size: usize) -> *mut c_void {
    if size != 0 {
        size = LAYOUT_OFFSET.saturating_add(DEFAULT_ALIGNMENT.next(size));

        if let Ok(layout) = Layout::from_size_align(size, DEFAULT_ALIGNMENT.into_raw()) {
            let mem = alloc::alloc::alloc(layout);
            if !mem.is_null() {
                ptr::write(mem as *mut usize, size);
                return mem.add(LAYOUT_OFFSET) as _;
            }
        }
    }

    unlikely_null()
}

/// Baseline `realloc` with the Rust allocator. `old_ptr` must be non-null and
/// `new_size` non-zero; the C wrapper handles those edge cases.
#[inline]
unsafe fn rust_realloc(mut old_ptr: *mut c_void, mut new_size: usize) -> *mut c_void {
    if new_size != 0 {
        new_size = LAYOUT_OFFSET.saturating_add(DEFAULT_ALIGNMENT.next(new_size));

        old_ptr = (old_ptr as *mut u8).offset(-(LAYOUT_OFFSET as isize)) as _;
        let size = ptr::read(old_ptr as *const usize);
        let layout = Layout::from_size_align_unchecked(size, DEFAULT_ALIGNMENT.into_raw());
        let new_ptr = alloc::alloc::realloc(old_ptr as _, layout, new_size);
        if !new_ptr.is_null() {
            ptr::write(new_ptr as *mut usize, new_size);
            return new_ptr.add(LAYOUT_OFFSET) as _;
        }
    }

    unlikely_null()
}

/// Baseline `free` with the Rust allocator. Does nothing if `mem` is null.
#[inline]
unsafe fn rust_free(mem: *mut c_void) {
    if !mem.is_null() {
        let mem = (mem as *mut u8).offset(-(LAYOUT_OFFSET as isize));
        let size = ptr::read(mem as *const usize);
        let layout = Layout::from_size_align_unchecked(size, DEFAULT_ALIGNMENT.into_raw());
        alloc::alloc::dealloc(mem, layout);
    }
}

// --- C ABI ----------------------------------------------------------------
//
// These are the symbols picolibc and other linked C code resolve against.

/// C `malloc`.
#[no_mangle]
pub unsafe extern "C" fn malloc(size: usize) -> *mut c_void {
    rust_malloc(size)
}

/// C `free`.
#[no_mangle]
pub unsafe extern "C" fn free(ptr: *mut c_void) {
    rust_free(ptr)
}

/// C `realloc`, with the standard edge cases: a null pointer behaves like
/// `malloc`, and a zero size frees and returns NULL.
#[no_mangle]
pub unsafe extern "C" fn realloc(ptr: *mut c_void, size: usize) -> *mut c_void {
    if ptr.is_null() {
        return rust_malloc(size);
    }
    if size == 0 {
        rust_free(ptr);
        return unlikely_null();
    }
    rust_realloc(ptr, size)
}

/// C `calloc`: allocates `nmemb * size` zeroed bytes, returning NULL on
/// multiplication overflow.
#[no_mangle]
pub unsafe extern "C" fn calloc(nmemb: usize, size: usize) -> *mut c_void {
    match nmemb.checked_mul(size) {
        Some(0) | None => unlikely_null(),
        Some(total) => {
            let ptr = rust_malloc(total);
            if !ptr.is_null() {
                // `get_ptr_size` returns the padded capacity (>= total); zeroing
                // the whole block is fine and matches malloc-rust's `rust_calloc`.
                ptr::write_bytes(ptr as *mut u8, 0, get_ptr_size(ptr));
            }
            ptr
        }
    }
}
